on:
    workflow_dispatch:
name: Release manually
jobs:
    publish_on_linux:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@master
              with:
                  node-version: 18
            - name: install dependencies
              run: npm install
            - name: publish
              env:
                  GITHUB_TOKEN: ${{ secrets.TOKEN }}
              run: npm run publish

    publish_on_mac:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@master
              with:
                  node-version: 18
            - name: install dependencies
              run: npm install
            - name: publish
              env:
                  GITHUB_TOKEN: ${{ secrets.TOKEN }}
              run: npm run publish

    publish_on_win:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@master
              with:
                  node-version: 18
            - name: Install Chocolatey
              shell: powershell
              run: Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
            - name: Install Wix Toolset
              run: choco install -y wixtoolset
            - name: Add env wixtools
              run: echo "C:\Program Files (x86)\WiX Toolset v3.11\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
            - name: smoke test
              shell: cmd
              run: candle -?
            - name: install dependencies
              run: npm install
            - name: publish
              env:
                  GITHUB_TOKEN: ${{ secrets.TOKEN }}
              run: npm run publish
